[config]
bm_open_method=0
[desktop]
wallpaper_mode=crop
wallpaper_common=1
wallpaper=/usr/share/backgrounds/blue/blue-wallpaper.png
desktop_bg=#080f1c
desktop_fg=#edf5ff
desktop_shadow=#080f1c
desktop_font=DejaVu Sans 10
show_wm_menu=1
show_documents=0
show_trash=1
show_mounts=1
